FROM polyaxon/polyaxon-npm-base

# This dockerfile is intended for dev only purposes
LABEL maintainer="Polyaxon, Inc. <contact@polyaxon.com>"

RUN apt-get -y update && \
    apt-get -y install nginx && \
    apt-get -y install libldap2-dev libsasl2-dev && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY /requirements /base/requirements
COPY /src/base/requirements/requirements-test.txt /base/requirements/
RUN pip3 install --no-cache-dir -r /base/requirements/core.txt
RUN pip3 install --no-cache-dir -r /base/requirements/test.txt
RUN pip3 install --no-cache-dir -r /base/requirements/requirements-test.txt
RUN pip3 install polyaxon
RUN rm -rf /base

COPY /src/coreapi/requirements /requirements/
RUN pip3 install --no-cache-dir -r /requirements/requirements-dev.txt

VOLUME /polyaxon
COPY /src /polyaxon/platform
WORKDIR /polyaxon

ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/platform/polycommon"
ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/platform/coredb"

WORKDIR /polyaxon/platform/coreapi
