export enum actionTypes {
  CREATE_STORE_REQUEST = 'CREATE_STORE_REQUEST',
  CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS',
  CREATE_STORE_ERROR = 'CREATE_STORE_ERROR',

  DELETE_STORE_REQUEST = 'DELETE_STORE_REQUEST',
  DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS',
  DELETE_STORE_ERROR = 'DELETE_STORE_ERROR',

  UPDATE_STORE_REQUEST = 'UPDATE_STORE_REQUEST',
  UPDATE_STORE_SUCCESS = 'UPDATE_STORE_SUCCESS',
  UPDATE_STORE_ERROR = 'UPDATE_STORE_ERROR',

  GET_STORE_REQUEST = 'GET_STORE_REQUEST',
  GET_STORE_SUCCESS = 'GET_STORE_SUCCESS',
  GET_STORE_ERROR = 'GET_STORE_ERROR',

  FETCH_STORES_REQUEST = 'FETCH_STORES_REQUEST',
  FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS',
  FETCH_STORES_ERROR = 'FETCH_STORES_ERROR',

  INIT_STORE_REQUEST = 'INIT_STORE_REQUEST',
}
