export enum actionTypes {
  CREATE_K8S_RESOURCE_REQUEST = 'CREATE_K8S_RESOURCE_REQUEST',
  CREATE_K8S_RESOURCE_SUCCESS = 'CREATE_K8S_RESOURCE_SUCCESS',
  CREATE_K8S_RESOURCE_ERROR = 'CREATE_K8S_RESOURCE_ERROR',

  DELETE_K8S_RESOURCE_REQUEST = 'DELETE_K8S_RESOURCE_REQUEST',
  DELETE_K8S_RESOURCE_SUCCESS = 'DELETE_K8S_RESOURCE_SUCCESS',
  DELETE_K8S_RESOURCE_ERROR = 'DELETE_K8S_RESOURCE_ERROR',

  UPDATE_K8S_RESOURCE_REQUEST = 'UPDATE_K8S_RESOURCE_REQUEST',
  UPDATE_K8S_RESOURCE_SUCCESS = 'UPDATE_K8S_RESOURCE_SUCCESS',
  UPDATE_K8S_RESOURCE_ERROR = 'UPDATE_K8S_RESOURCE_ERROR',

  GET_K8S_RESOURCE_REQUEST = 'GET_K8S_RESOURCE_REQUEST',
  GET_K8S_RESOURCE_SUCCESS = 'GET_K8S_RESOURCE_SUCCESS',
  GET_K8S_RESOURCE_ERROR = 'GET_K8S_RESOURCE_ERROR',

  FETCH_K8S_RESOURCES_REQUEST = 'FETCH_K8S_RESOURCES_REQUEST',
  FETCH_K8S_RESOURCES_SUCCESS = 'FETCH_K8S_RESOURCES_SUCCESS',
  FETCH_K8S_RESOURCES_ERROR = 'FETCH_K8S_RESOURCES_ERROR',

  INIT_K8S_RESOURCE_REQUEST = 'INIT_K8S_RESOURCE_REQUEST',
}
