export enum actionTypes {
  CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR',

  DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST',
  DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR',

  UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR',

  ARCHIVE_PROJECT_REQUEST = 'ARCHIVE_PROJECT_REQUEST',
  ARCHIVE_PROJECT_SUCCESS = 'ARCHIVE_PROJECT_SUCCESS',
  ARCHIVE_PROJECT_ERROR = 'ARCHIVE_PROJECT_ERROR',

  RESTORE_PROJECT_REQUEST = 'RESTORE_PROJECT_REQUEST',
  RESTORE_PROJECT_SUCCESS = 'RESTORE_PROJECT_SUCCESS',
  RESTORE_PROJECT_ERROR = 'RESTORE_PROJECT_ERROR',

  GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST',
  GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS',
  GET_PROJECT_ERROR = 'GET_PROJECT_ERROR',

  FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_ERROR = 'FETCH_PROJECTS_ERROR',

  BOOKMARK_PROJECT_REQUEST = 'BOOKMARK_PROJECT_REQUEST',
  BOOKMARK_PROJECT_SUCCESS = 'BOOKMARK_PROJECT_SUCCESS',
  BOOKMARK_PROJECT_ERROR = 'BOOKMARK_PROJECT_ERROR',

  UNBOOKMARK_PROJECT_REQUEST = 'UNBOOKMARK_PROJECT_REQUEST',
  UNBOOKMARK_PROJECT_SUCCESS = 'UNBOOKMARK_PROJECT_SUCCESS',
  UNBOOKMARK_PROJECT_ERROR = 'UNBOOKMARK_PROJECT_ERROR',

  START_PROJECT_NOTEBOOK_REQUEST = 'START_PROJECT_NOTEBOOK_REQUEST',
  START_PROJECT_NOTEBOOK_SUCCESS = 'START_PROJECT_NOTEBOOK_SUCCESS',
  START_PROJECT_NOTEBOOK_ERROR = 'START_PROJECT_NOTEBOOK_ERROR',

  STOP_PROJECT_NOTEBOOK_REQUEST = 'STOP_PROJECT_NOTEBOOK_REQUEST',
  STOP_PROJECT_NOTEBOOK_SUCCESS = 'STOP_PROJECT_NOTEBOOK_SUCCESS',
  STOP_PROJECT_NOTEBOOK_ERROR = 'STOP_PROJECT_NOTEBOOK_ERROR',

  START_PROJECT_TENSORBOARD_REQUEST = 'START_PROJECT_TENSORBOARD_REQUEST',
  START_PROJECT_TENSORBOARD_SUCCESS = 'START_PROJECT_TENSORBOARD_SUCCESS',
  START_PROJECT_TENSORBOARD_ERROR = 'START_PROJECT_TENSORBOARD_ERROR',

  STOP_PROJECT_TENSORBOARD_REQUEST = 'STOP_PROJECT_TENSORBOARD_REQUEST',
  STOP_PROJECT_TENSORBOARD_SUCCESS = 'STOP_PROJECT_TENSORBOARD_SUCCESS',
  STOP_PROJECT_TENSORBOARD_ERROR = 'STOP_PROJECT_TENSORBOARD_ERROR',
}
