FROM polyaxon-base-dev

# This dockerfile is intended for dev only purposes
LABEL maintainer="Polyaxon, Inc. <contact@polyaxon.com>"

VOLUME /polyaxon
COPY /core /polyaxon/core
COPY /sdks/python/http_client/v1 /polyaxon/sdks/python/http_client/v1
COPY /platform /polyaxon/platform
WORKDIR /polyaxon

ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/sdks/python/http_client/v1"
ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/core"
ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/platform/polycommon"
ENV PYTHONPATH="${PYTHONPATH}:/polyaxon/platform/coredb"

WORKDIR /polyaxon/platform/core-scheduler
