USER_REGISTER = 'user.register'
USER_PASSWORD_UPDATE = 'user.password_update'
USER_ACTIVATED = 'user.activate'
USER_DELETE = 'user.delete'
SUPERUSER_ROLE_GRANT = 'superuser.role.grant'
SUPERUSER_ROLE_REVOKE = 'superuser.role.revoke'
CLUSTER_CREATE = 'cluster.create'
CLUSTER_UPDATE = 'cluster.update'
CLUSTER_NODE_CREATE = 'cluster.node.create'
CLUSTER_NODE_UPDATE = 'cluster.node.update'
CLUSTER_NODE_DELETE = 'cluster.node.delete'
PROJECT_CREATE = 'project.create'
PROJECT_UPDATE = 'project.update'
PROJECT_SET_PUBLIC = 'project.set_public'  # params same user, other user, access granted
PROJECT_SET_PRIVATE = 'project.set_private'  # params same user, other user, access granted
PROJECT_DELETE = 'project.delete'  # params same user, other user, access granted
PROJECT_VIEW = 'project.view'  # params same user, other user, access granted
PROJECT_EXPERIMENTS_VIEW = 'project.experiments_view'
PROJECT_EXPERIMENT_GROUPS_VIEW = 'project.experiment_groups_view'
REPO_CREATE = 'repo.create'
REPO_NEW_COMMIT = 'repo.new_commit'  # attempt, fullfilled
EXPERIMENT_GROUP_CREATE = 'experiment_group.create'
EXPERIMENT_GROUP_UPDATE = 'experiment_group.update'
EXPERIMENT_GROUP_DELETE = 'experiment_group.delete'
EXPERIMENT_GROUP_VIEW = 'experiment_group.view'
EXPERIMENT_GROUP_STOP = 'experiment_group.stop'
EXPERIMENT_GROUP_RESUME = 'experiment_group.resume'
EXPERIMENT_GROUP_RANDOM = 'experiment_group.random'
EXPERIMENT_GROUP_GRID = 'experiment_group.grid'
EXPERIMENT_GROUP_HYPERBAND = 'experiment_group.hyperband'
EXPERIMENT_GROUP_BO = 'experiment_group.bo'
EXPERIMENT_GROUP_ITERATION = 'experiment_group.iteration'
EXPERIMENT_GROUP_FINISH = 'experiment_group.finish'
EXPERIMENT_EXPERIMENTS = 'experiment_group.experiments'
EXPERIMENT_CREATE = 'experiment.create'
EXPERIMENT_UPDATE = 'experiment.update'  # params same user, other user, access granted
EXPERIMENT_DELETE = 'experiment.delete'  # params same user, other user, access granted
EXPERIMENT_VIEW = 'experiment.view'  # params same user, other user, access granted
EXPERIMENT_STOP = 'experiment.stop'  # params same user, other user, access granted
EXPERIMENT_RESUME = 'experiment.resume'  # params same user, other user, access granted
EXPERIMENT_RESTART = 'experiment.restart'  # params same user, other user, access granted
EXPERIMENT_COPY = 'experiment.copy'  # params same user, other user, access granted
EXPERIMENT_SUCCESS = 'experiment.success'
EXPERIMENT_FAILURE = 'experiment.failure'
EXPERIMENT_RESOURCES_VIEW = 'experiment.resources_view'  # params same user, other user, access granted
EXPERIMENT_LOGS_VIEW = 'experiment.logs_view'  # params same user, other user, access granted
EXPERIMENT_STATUSES_VIEW = 'experiment.statuses_view'
EXPERIMENT_JOB_VIEW = 'experiment.job.view'  # params same user, other user, access granted
EXPERIMENT_JOB_RESOURCES_VIEW = 'experiment.job.resources_view'  # params same user, other user, access granted
EXPERIMENT_JOB_LOGS_VIEW = 'experiment.job.logs_view'  # params same user, other user, access granted
EXPERIMENT_JOB_STATUSES_VIEW = 'experiment.job.statuses_view'
TENSORBOARD_START = 'tensorboard.start'
TENSORBOARD_STOP = 'tensorboard.stop'
NOTEBOOK_START = 'notebook.start'
NOTEBOOK_STOP = 'notebook.stop'
