USER_REGISTERED = 'user.registered'
USER_PASSWORD_UPDATED = 'user.password_updated'
USER_ACTIVATED = 'user.activated'
USER_DELETED = 'user.deleted'
SUPERUSER_ROLE_GRANTED = 'superuser.role.granted'
SUPERUSER_ROLE_REVOKED = 'superuser.role.revoked'
CLUSTER_CREATED = 'cluster.created'
CLUSTER_UPDATED = 'cluster.updated'
CLUSTER_NODE_CREATED = 'cluster.node.created'
CLUSTER_NODE_UPDATED = 'cluster.node.updated'
CLUSTER_NODE_DELETED = 'cluster.node.deleted'
PROJECT_CREATED = 'project.created'
PROJECT_UPDATED = 'project.updated'
PROJECT_SET_PUBLIC = 'project.set_public'  # params same user, other user, access granted
PROJECT_SET_PRIVATE = 'project.set_private'  # params same user, other user, access granted
PROJECT_DELETED = 'project.deleted'  # params same user, other user, access granted
PROJECT_VIEWED = 'project.viewed'  # params same user, other user, access granted
PROJECT_EXPERIMENTS_VIEWED = 'project.experiments_viewed'
PROJECT_EXPERIMENT_GROUPS_VIEWED = 'project.experiment_groups_viewed'
REPO_CREATED = 'repo.created'
REPO_NEW_COMMIT = 'repo.new_commit'  # attempt, fullfilled
EXPERIMENT_GROUP_CREATED = 'experiment_group.created'
EXPERIMENT_GROUP_UPDATED = 'experiment_group.updated'
EXPERIMENT_GROUP_DELETED = 'experiment_group.deleted'
EXPERIMENT_GROUP_VIEWED = 'experiment_group.viewed'
EXPERIMENT_GROUP_STOPPED = 'experiment_group.stopped'
EXPERIMENT_GROUP_RESUMED = 'experiment_group.resumed'
EXPERIMENT_GROUP_RANDOM = 'experiment_group.random'
EXPERIMENT_GROUP_GRID = 'experiment_group.grid'
EXPERIMENT_GROUP_HYPERBAND = 'experiment_group.hyperband'
EXPERIMENT_GROUP_BO = 'experiment_group.bo'
EXPERIMENT_GROUP_ITERATION = 'experiment_group.iteration'
EXPERIMENT_GROUP_FINISHED = 'experiment_group.finished'
EXPERIMENT_GROUP_EXPERIMENTS = 'experiment_group.experiments'
EXPERIMENT_CREATED = 'experiment.created'
EXPERIMENT_UPDATED = 'experiment.updated'  # params same user, other user, access granted
EXPERIMENT_DELETED = 'experiment.deleted'  # params same user, other user, access granted
EXPERIMENT_VIEWED = 'experiment.viewed'  # params same user, other user, access granted
EXPERIMENT_STOPPED = 'experiment.stopped'  # params same user, other user, access granted
EXPERIMENT_RESUMED = 'experiment.resumed'  # params same user, other user, access granted
EXPERIMENT_RESTARTED = 'experiment.restarted'  # params same user, other user, access granted
EXPERIMENT_COPIED = 'experiment.copied'  # params same user, other user, access granted
EXPERIMENT_NEW_STATUS = 'experiment.new_status'
EXPERIMENT_SUCCEEDED = 'experiment.succeeded'
EXPERIMENT_FAILED = 'experiment.failed'
EXPERIMENT_RESOURCES_VIEWED = 'experiment.resources_viewed'  # params same user, other user, access granted
EXPERIMENT_LOGS_VIEWED = 'experiment.logs_viewed'  # params same user, other user, access granted
EXPERIMENT_STATUSES_VIEWED = 'experiment.statuses_viewed'
EXPERIMENT_JOBS_VIEWED = 'experiment.jobs_viewed'
EXPERIMENT_JOB_VIEWED = 'experiment.job.viewed'  # params same user, other user, access granted
EXPERIMENT_JOB_RESOURCES_VIEWED = 'experiment.job.resources_viewed'  # params same user, other user, access granted
EXPERIMENT_JOB_LOGS_VIEWED = 'experiment.job.logs_viewed'  # params same user, other user, access granted
EXPERIMENT_JOB_STATUSES_VIEWED = 'experiment.job.statuses_viewed'
TENSORBOARD_STARTED = 'tensorboard.started'
TENSORBOARD_STOPPED = 'tensorboard.stopped'
TENSORBOARD_NEW_STATUS = 'tensorboard.new_status'
NOTEBOOK_STARTED = 'notebook.started'
NOTEBOOK_STOPPED = 'notebook.stopped'
NOTEBOOK_NEW_STATUS = 'notebook.new_status'
