output-format: grouped

strictness: high
test-warnings: false
doc-warnings: true

max-line-length: 100


ignore-patterns:
  - __init__.py

pep257:
  run: false

mccabe:
  run: false

pylint:
  disable:
    - abstract-method
    - broad-except
    - cyclic-import
    - invalid-name
    - missing-docstring
    - no-init
    - no-self-use
    - old-style-class
    - redefined-variable-type
    - too-many-ancestors
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-locals
    - unused-argument
  enable:
    - missing-final-newline
  options:
    ignore: migrations
