import executor

from events.registry import tensorboard

executor.subscribe(tensorboard.TensorboardStartedEvent)
executor.subscribe(tensorboard.TensorboardSoppedEvent)
executor.subscribe(tensorboard.TensorboardCleanedTriggeredEvent)
executor.subscribe(tensorboard.TensorboardNewStatusEvent)
executor.subscribe(tensorboard.TensorboardFailedEvent)
executor.subscribe(tensorboard.TensorboardSucceededEvent)
