from hestia.unknown import UNKNOWN

from lifecycles.statuses import BaseStatuses, StatusOptions


class PipelineLifeCycle(BaseStatuses):
    CREATED = StatusOptions.CREATED
    WARNING = StatusOptions.WARNING
    SCHEDULED = StatusOptions.SCHEDULED
    RUNNING = StatusOptions.RUNNING
    DONE = StatusOptions.DONE
    STOPPED = StatusOptions.STOPPED
    STOPPING = StatusOptions.STOPPING
    SKIPPED = StatusOptions.SKIPPED
    FAILED = StatusOptions.FAILED
    UPSTREAM_FAILED = StatusOptions.UPSTREAM_FAILED
    UNKNOWN = UNKNOWN

    CHOICES = (
        (CREATED, CREATED),
        (WARNING, WARNING),
        (SCHEDULED, SCHEDULED),
        (RUNNING, RUNNING),
        (DONE, DONE),
        (FAILED, FAILED),
        (UPSTREAM_FAILED, UPSTREAM_FAILED),
        (STOPPED, STOPPED),
        (STOPPING, STOPPING),
        (SKIPPED, SKIPPED),
        (UNKNOWN, UNKNOWN),
    )

    VALUES = {
        CREATED,
        WARNING,
        SCHEDULED,
        RUNNING,
        DONE,
        FAILED,
        UPSTREAM_FAILED,
        STOPPED,
        STOPPING,
        SKIPPED,
        UNKNOWN
    }

    HEARTBEAT_STATUS = set([])
    WARNING_STATUS = {WARNING, }
    STARTING_STATUS = {CREATED, }
    RUNNING_STATUS = {SCHEDULED, RUNNING, STOPPING, }
    DONE_STATUS = {FAILED, UPSTREAM_FAILED, DONE, STOPPED, SKIPPED, }
    FAILED_STATUS = {FAILED, UPSTREAM_FAILED, }

    TRANSITION_MATRIX = {
        CREATED: {None, },
        SCHEDULED: {CREATED, WARNING, },
        RUNNING: {SCHEDULED, WARNING, },
        WARNING: set(VALUES) - {DONE, STOPPED, SKIPPED, STOPPED, WARNING, },
        DONE: set(VALUES) - DONE_STATUS,
        FAILED: set(VALUES) - DONE_STATUS,
        UPSTREAM_FAILED: set(VALUES) - DONE_STATUS,
        STOPPED: set(VALUES) - DONE_STATUS,
        STOPPING: VALUES - DONE_STATUS - {STOPPING, },
        SKIPPED: set(VALUES) - DONE_STATUS,
        UNKNOWN: VALUES - {UNKNOWN, },
    }


class OperationStatuses(BaseStatuses):
    CREATED = StatusOptions.CREATED
    WARNING = StatusOptions.WARNING
    SCHEDULED = StatusOptions.SCHEDULED
    RUNNING = StatusOptions.RUNNING
    SUCCEEDED = StatusOptions.SUCCEEDED
    FAILED = StatusOptions.FAILED
    UPSTREAM_FAILED = StatusOptions.UPSTREAM_FAILED
    STOPPED = StatusOptions.STOPPED
    SKIPPED = StatusOptions.SKIPPED
    RETRYING = StatusOptions.RETRYING

    VALUES = {
        CREATED, WARNING, SCHEDULED, RUNNING,
        SUCCEEDED, FAILED, UPSTREAM_FAILED, STOPPED, SKIPPED, RETRYING
    }
    CHOICES = (
        (CREATED, CREATED),
        (WARNING, WARNING),
        (SCHEDULED, SCHEDULED),
        (RUNNING, RUNNING),
        (SUCCEEDED, SUCCEEDED),
        (FAILED, FAILED),
        (UPSTREAM_FAILED, UPSTREAM_FAILED),
        (STOPPED, STOPPED),
        (SKIPPED, SKIPPED),
        (RETRYING, RETRYING)
    )

    DONE_STATUS = {SUCCEEDED, FAILED, UPSTREAM_FAILED, STOPPED, SKIPPED}
    RUNNING_STATUS = {SCHEDULED, RUNNING}
    FAILED_STATUS = {FAILED, UPSTREAM_FAILED}

    TRANSITION_MATRIX = {
        CREATED: {None, },
        SCHEDULED: {CREATED, RETRYING, WARNING, },
        RUNNING: {SCHEDULED, WARNING, },
        SUCCEEDED: {RUNNING, WARNING, },
        FAILED: {SCHEDULED, RUNNING, WARNING, },
        UPSTREAM_FAILED: set(VALUES) - {UPSTREAM_FAILED, },
        STOPPED: {CREATED, SCHEDULED, RUNNING, WARNING, },
        SKIPPED: {CREATED, SCHEDULED, STOPPED, WARNING, },
        RETRYING: {SCHEDULED, RUNNING, FAILED, STOPPED, SKIPPED, RETRYING, WARNING, },
        WARNING: set(VALUES) - {SUCCEEDED, FAILED, STOPPED, UPSTREAM_FAILED, WARNING, },
    }


class TriggerPolicy(object):
    ALL_SUCCEEDED = 'all_succeeded'
    ALL_FAILED = 'all_failed'
    ALL_DONE = 'all_done'
    ONE_SUCCEEDED = 'one_succeeded'
    ONE_FAILED = 'one_failed'
    ONE_DONE = 'one_done'

    VALUES = {ALL_SUCCEEDED, ALL_FAILED, ALL_DONE, ONE_SUCCEEDED, ONE_FAILED, ONE_DONE}
    CHOICES = (
        (ALL_SUCCEEDED, ALL_SUCCEEDED),
        (ALL_FAILED, ALL_FAILED),
        (ALL_DONE, ALL_DONE),
        (ONE_SUCCEEDED, ONE_SUCCEEDED),
        (ONE_FAILED, ONE_FAILED),
        (ONE_DONE, ONE_DONE),
    )
