CREATED = 'created'
UPDATED = 'updated'
DELETED = 'deleted'
CLEANED = 'cleaned'
VIEWED = 'viewed'
ARCHIVED = 'archived'
RESTORED = 'restored'
DENIED = 'denied'
REGISTERED = 'registered'
ACTIVATED = 'activated'
GRANTED = 'granted'
REVOKED = 'revoked'
INVITED = 'invited'
CLONED = 'cloned'
RESUMED = 'resumed'
STARTED = 'started'
RESTARTED = 'restarted'
COPIED = 'copied'
SUCCEEDED = 'succeeded'
FAILED = 'failed'
DONE = 'done'
STOPPED = 'stopped'
DOWNLOADED = 'downloaded'
BOOKMARKED = 'bookmarked'
UNBOOKMARKED = 'unbookmarked'
NEW_STATUS = 'new_status'
NEW_METRIC = 'new_metric'
OUTPUTS_DOWNLOADED = 'outputs_downloaded'
RESOURCES_VIEWED = 'resources_viewed'
LOGS_VIEWED = 'logs_viewed'
STATUSES_VIEWED = 'statuses_viewed'
JOBS_VIEWED = 'jobs_viewed'
BUILDS_VIEWED = 'builds_viewed'
TENSORBOARDS_VIEWED = 'tensorboards_viewed'
METRICS_VIEWED = 'metrics_viewed'
EXPERIMENTS_VIEWED = 'experiments_viewed'
EXPERIMENT_GROUPS_VIEWED = 'experiment_groups_viewed'
PROJECTS_VIEWED = 'projects_viewed'
EXECUTED = 'executed'
AUTH = 'auth'
LDAP = 'ldap'
GITHUB = 'github'
GITLAB = 'gitlab'
BITBUCKET = 'bitbucket'
AZURE = 'azure'

WRITE_ACTIONS = [
    CREATED,
    UPDATED,
    DELETED,
    RESUMED,
    COPIED,
    CLONED,
    STOPPED,
]
