apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-repos
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.138.0.3  # Use the right IP
    path: "/data/repos"
  claimRef:
    namespace: polyaxon 
    name: polyaxon-pvc-repos
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-repos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
