// Copyright 2019 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package config_resources_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	service_model "github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// ListConfigResourcesReader is a Reader for the ListConfigResources structure.
type ListConfigResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListConfigResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListConfigResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewListConfigResourcesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewListConfigResourcesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListConfigResourcesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListConfigResourcesOK creates a ListConfigResourcesOK with default headers values
func NewListConfigResourcesOK() *ListConfigResourcesOK {
	return &ListConfigResourcesOK{}
}

/*ListConfigResourcesOK handles this case with default header values.

A successful response.
*/
type ListConfigResourcesOK struct {
	Payload *service_model.V1ListConfigResourcesResponse
}

func (o *ListConfigResourcesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/config_resources][%d] listConfigResourcesOK  %+v", 200, o.Payload)
}

func (o *ListConfigResourcesOK) GetPayload() *service_model.V1ListConfigResourcesResponse {
	return o.Payload
}

func (o *ListConfigResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1ListConfigResourcesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigResourcesNoContent creates a ListConfigResourcesNoContent with default headers values
func NewListConfigResourcesNoContent() *ListConfigResourcesNoContent {
	return &ListConfigResourcesNoContent{}
}

/*ListConfigResourcesNoContent handles this case with default header values.

No content.
*/
type ListConfigResourcesNoContent struct {
	Payload interface{}
}

func (o *ListConfigResourcesNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/config_resources][%d] listConfigResourcesNoContent  %+v", 204, o.Payload)
}

func (o *ListConfigResourcesNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *ListConfigResourcesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigResourcesForbidden creates a ListConfigResourcesForbidden with default headers values
func NewListConfigResourcesForbidden() *ListConfigResourcesForbidden {
	return &ListConfigResourcesForbidden{}
}

/*ListConfigResourcesForbidden handles this case with default header values.

You don't have permission to access the resource.
*/
type ListConfigResourcesForbidden struct {
	Payload interface{}
}

func (o *ListConfigResourcesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/config_resources][%d] listConfigResourcesForbidden  %+v", 403, o.Payload)
}

func (o *ListConfigResourcesForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *ListConfigResourcesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigResourcesNotFound creates a ListConfigResourcesNotFound with default headers values
func NewListConfigResourcesNotFound() *ListConfigResourcesNotFound {
	return &ListConfigResourcesNotFound{}
}

/*ListConfigResourcesNotFound handles this case with default header values.

Resource does not exist.
*/
type ListConfigResourcesNotFound struct {
	Payload interface{}
}

func (o *ListConfigResourcesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/config_resources][%d] listConfigResourcesNotFound  %+v", 404, o.Payload)
}

func (o *ListConfigResourcesNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ListConfigResourcesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
