// Copyright 2018-2020 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package runs_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// RunsV1CreateRunReader is a Reader for the RunsV1CreateRun structure.
type RunsV1CreateRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunsV1CreateRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRunsV1CreateRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewRunsV1CreateRunNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewRunsV1CreateRunForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRunsV1CreateRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewRunsV1CreateRunDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRunsV1CreateRunOK creates a RunsV1CreateRunOK with default headers values
func NewRunsV1CreateRunOK() *RunsV1CreateRunOK {
	return &RunsV1CreateRunOK{}
}

/*RunsV1CreateRunOK handles this case with default header values.

A successful response.
*/
type RunsV1CreateRunOK struct {
	Payload *service_model.V1Run
}

func (o *RunsV1CreateRunOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/{project}/runs][%d] runsV1CreateRunOK  %+v", 200, o.Payload)
}

func (o *RunsV1CreateRunOK) GetPayload() *service_model.V1Run {
	return o.Payload
}

func (o *RunsV1CreateRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1Run)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsV1CreateRunNoContent creates a RunsV1CreateRunNoContent with default headers values
func NewRunsV1CreateRunNoContent() *RunsV1CreateRunNoContent {
	return &RunsV1CreateRunNoContent{}
}

/*RunsV1CreateRunNoContent handles this case with default header values.

No content.
*/
type RunsV1CreateRunNoContent struct {
	Payload interface{}
}

func (o *RunsV1CreateRunNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/{project}/runs][%d] runsV1CreateRunNoContent  %+v", 204, o.Payload)
}

func (o *RunsV1CreateRunNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *RunsV1CreateRunNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsV1CreateRunForbidden creates a RunsV1CreateRunForbidden with default headers values
func NewRunsV1CreateRunForbidden() *RunsV1CreateRunForbidden {
	return &RunsV1CreateRunForbidden{}
}

/*RunsV1CreateRunForbidden handles this case with default header values.

You don't have permission to access the resource.
*/
type RunsV1CreateRunForbidden struct {
	Payload interface{}
}

func (o *RunsV1CreateRunForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/{project}/runs][%d] runsV1CreateRunForbidden  %+v", 403, o.Payload)
}

func (o *RunsV1CreateRunForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *RunsV1CreateRunForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsV1CreateRunNotFound creates a RunsV1CreateRunNotFound with default headers values
func NewRunsV1CreateRunNotFound() *RunsV1CreateRunNotFound {
	return &RunsV1CreateRunNotFound{}
}

/*RunsV1CreateRunNotFound handles this case with default header values.

Resource does not exist.
*/
type RunsV1CreateRunNotFound struct {
	Payload interface{}
}

func (o *RunsV1CreateRunNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/{project}/runs][%d] runsV1CreateRunNotFound  %+v", 404, o.Payload)
}

func (o *RunsV1CreateRunNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *RunsV1CreateRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsV1CreateRunDefault creates a RunsV1CreateRunDefault with default headers values
func NewRunsV1CreateRunDefault(code int) *RunsV1CreateRunDefault {
	return &RunsV1CreateRunDefault{
		_statusCode: code,
	}
}

/*RunsV1CreateRunDefault handles this case with default header values.

An unexpected error response
*/
type RunsV1CreateRunDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// Code gets the status code for the runs v1 create run default response
func (o *RunsV1CreateRunDefault) Code() int {
	return o._statusCode
}

func (o *RunsV1CreateRunDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/{project}/runs][%d] RunsV1_CreateRun default  %+v", o._statusCode, o.Payload)
}

func (o *RunsV1CreateRunDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *RunsV1CreateRunDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
