// Copyright 2018-2020 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package runs_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// NewRunsV1CreateRunParams creates a new RunsV1CreateRunParams object
// with the default values initialized.
func NewRunsV1CreateRunParams() *RunsV1CreateRunParams {
	var ()
	return &RunsV1CreateRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRunsV1CreateRunParamsWithTimeout creates a new RunsV1CreateRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRunsV1CreateRunParamsWithTimeout(timeout time.Duration) *RunsV1CreateRunParams {
	var ()
	return &RunsV1CreateRunParams{

		timeout: timeout,
	}
}

// NewRunsV1CreateRunParamsWithContext creates a new RunsV1CreateRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewRunsV1CreateRunParamsWithContext(ctx context.Context) *RunsV1CreateRunParams {
	var ()
	return &RunsV1CreateRunParams{

		Context: ctx,
	}
}

// NewRunsV1CreateRunParamsWithHTTPClient creates a new RunsV1CreateRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRunsV1CreateRunParamsWithHTTPClient(client *http.Client) *RunsV1CreateRunParams {
	var ()
	return &RunsV1CreateRunParams{
		HTTPClient: client,
	}
}

/*RunsV1CreateRunParams contains all the parameters to send to the API endpoint
for the runs v1 create run operation typically these are written to a http.Request
*/
type RunsV1CreateRunParams struct {

	/*Body
	  operation object

	*/
	Body *service_model.V1OperationBody
	/*Owner
	  Owner of the namespace

	*/
	Owner string
	/*Project
	  Project where the run will be assigned

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithTimeout(timeout time.Duration) *RunsV1CreateRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithContext(ctx context.Context) *RunsV1CreateRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithHTTPClient(client *http.Client) *RunsV1CreateRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithBody(body *service_model.V1OperationBody) *RunsV1CreateRunParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetBody(body *service_model.V1OperationBody) {
	o.Body = body
}

// WithOwner adds the owner to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithOwner(owner string) *RunsV1CreateRunParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithProject adds the project to the runs v1 create run params
func (o *RunsV1CreateRunParams) WithProject(project string) *RunsV1CreateRunParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the runs v1 create run params
func (o *RunsV1CreateRunParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *RunsV1CreateRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
