// Copyright 2019 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package registry_accesses_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	service_model "github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// NewCreateRegistryAccessParams creates a new CreateRegistryAccessParams object
// with the default values initialized.
func NewCreateRegistryAccessParams() *CreateRegistryAccessParams {
	var ()
	return &CreateRegistryAccessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRegistryAccessParamsWithTimeout creates a new CreateRegistryAccessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRegistryAccessParamsWithTimeout(timeout time.Duration) *CreateRegistryAccessParams {
	var ()
	return &CreateRegistryAccessParams{

		timeout: timeout,
	}
}

// NewCreateRegistryAccessParamsWithContext creates a new CreateRegistryAccessParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRegistryAccessParamsWithContext(ctx context.Context) *CreateRegistryAccessParams {
	var ()
	return &CreateRegistryAccessParams{

		Context: ctx,
	}
}

// NewCreateRegistryAccessParamsWithHTTPClient creates a new CreateRegistryAccessParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRegistryAccessParamsWithHTTPClient(client *http.Client) *CreateRegistryAccessParams {
	var ()
	return &CreateRegistryAccessParams{
		HTTPClient: client,
	}
}

/*CreateRegistryAccessParams contains all the parameters to send to the API endpoint
for the create registry access operation typically these are written to a http.Request
*/
type CreateRegistryAccessParams struct {

	/*Body
	  Artifact store body

	*/
	Body *service_model.V1HostAccess
	/*Owner
	  Owner of the namespace

	*/
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create registry access params
func (o *CreateRegistryAccessParams) WithTimeout(timeout time.Duration) *CreateRegistryAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create registry access params
func (o *CreateRegistryAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create registry access params
func (o *CreateRegistryAccessParams) WithContext(ctx context.Context) *CreateRegistryAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create registry access params
func (o *CreateRegistryAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create registry access params
func (o *CreateRegistryAccessParams) WithHTTPClient(client *http.Client) *CreateRegistryAccessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create registry access params
func (o *CreateRegistryAccessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create registry access params
func (o *CreateRegistryAccessParams) WithBody(body *service_model.V1HostAccess) *CreateRegistryAccessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create registry access params
func (o *CreateRegistryAccessParams) SetBody(body *service_model.V1HostAccess) {
	o.Body = body
}

// WithOwner adds the owner to the create registry access params
func (o *CreateRegistryAccessParams) WithOwner(owner string) *CreateRegistryAccessParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the create registry access params
func (o *CreateRegistryAccessParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRegistryAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
