export enum actionTypes {
  POST_OPTIONS_REQUEST = 'POST_OPTIONS_REQUEST',
  POST_OPTIONS_SUCCESS = 'POST_OPTIONS_SUCCESS',
  POST_OPTIONS_ERROR = 'POST_OPTIONS_ERROR',

  FETCH_OPTIONS_REQUEST = 'FETCH_OPTIONS_REQUEST',
  FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS',
  FETCH_OPTIONS_ERROR = 'FETCH_OPTIONS_ERROR',
}
