import notifier

from events.registry import tensorboard

# notifier.subscribe_event(tensorboard.TensorboardNewStatusEvent)
notifier.subscribe_event(tensorboard.TensorboardStartedEvent)
notifier.subscribe_event(tensorboard.TensorboardSoppedEvent)
notifier.subscribe_event(tensorboard.TensorboardFailedEvent)
notifier.subscribe_event(tensorboard.TensorboardSucceededEvent)
