export const ACTIONS = {
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
  GET: 'get',
  FETCH: 'fetch',
  ARCHIVE: 'archive',
  RESTART: 'restart',
  RESUME: 'resume',
  RESTORE: 'restore',
  SET_GIT: 'setGit',
  STOP: 'stop',
  BOOKMARK: 'bookmark',
  UNBOOKMARK: 'unbookmark',
  START_NOTEBOOK: 'start_notebook',
  STOP_NOTEBOOK: 'stop_notebook',
  START_TENSORBOARD: 'start_tensorboard',
  STOP_TENSORBOARD: 'stop_tensorboard',
};
