---
version: 1

project:
  name: alexnet_flowers17

settings:
  logging:
    level: INFO

environment:
  run_config:
    save_summary_steps: 100
    save_checkpoints_steps: 100

model:
  classifier:
    loss:
      SigmoidCrossEntropy:
    optimizer:
      Momentum:
        learning_rate: 0.001
    metrics:
      - Accuracy
    one_hot_encode: true
    n_classes: 17
    graph:
      input_layers: image
      layers:
        - Conv2D:
            filters: 96
            kernel_size: 11
            strides: 4
            activation: relu
            regularizer:
                L2:
                  l: 0.02
        - MaxPooling2D:
            pool_size: 3
            strides: 2
        - Conv2D:
            filters: 156
            kernel_size: 5
            activation: relu
            regularizer:
                L2:
                  l: 0.02
        - MaxPooling2D:
            pool_size: 3
            strides: 2
        - Conv2D:
            filters: 384
            kernel_size: 3
            activation: relu
        - Conv2D:
            filters: 384
            kernel_size: 3
            activation: relu
        - Conv2D:
            filters: 256
            kernel_size: 3
            activation: relu
        - MaxPooling2D:
            pool_size: 3
            strides: 2
        - Flatten:
        - Dense:
            units: 4096
            activation: tanh
        - Dropout:
            rate: 0.5
        - Dense:
            units: 4096
            activation: tanh
        - Dropout:
            rate: 0.5
        - Dense:
            units: 17

train:
  train_steps: 100
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 64
      num_epochs: 1
      shuffle: true
      data_files: ["../data/flowers17/flowers_train.tfrecord"]
      meta_data_file: "../data/flowers17/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32


eval:
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 32
      num_epochs: 1
      shuffle: False
      data_files: ["../data/flowers17/flowers_eval.tfrecord"]
      meta_data_file: "../data/flowers17/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32
