---
version: 1

project:
  name: convnet_cifar10

settings:
  logging:
    level: INFO
    delay_workers_by_global_step: 10
    run_config:
      save_summary_steps: 100
      save_checkpoints_steps: 100

model:
  classifier:
    loss:
      SigmoidCrossEntropy:
    optimizer:
      Adam:
        learning_rate: 0.001
    metrics:
      - Accuracy
      - Precision
    one_hot_encode: true
    n_classes: 10
    graph:
      input_layers: image
      layers:
        - Conv2D:
            filters: 32
            kernel_size: 3
            strides: 1
            activation: relu
        - MaxPooling2D:
            pool_size: 2
        - Conv2D:
            filters: 64
            kernel_size: 3
            activation: relu
        - Conv2D:
            filters: 64
            kernel_size: 3
            activation: relu
        - MaxPooling2D:
            pool_size: 2
        - Flatten:
        - Dense:
            units: 512
            activation: relu
        - Dropout:
            rate: 0.5
        - Dense:
            units: 10

train:
  train_steps: 100
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 64
      num_epochs: 5
      shuffle: true
      data_files: ["../data/cifar10/cifar_train.tfrecord"]
      meta_data_file: "../data/cifar10/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32

eval:
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 32
      num_epochs: 1
      shuffle: False
      data_files: ["../data/cifar10/cifar_eval.tfrecord"]
      meta_data_file: "../data/cifar10/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32


