---
version: 1

project:
  name: vgg19

settings:
  logging:
    level: INFO

environment:
  run_config:
    save_summary_steps: 100
    save_checkpoints_steps: 100

model:
  classifier:
    loss:
      SigmoidCrossEntropy:
    optimizer:
      Adam:
        learning_rate: 0.001
    metrics:
      - Accuracy
      - Precision
    one_hot_encode: true
    n_classes: 10
    graph:
      input_layers: image
      layers:
        - Conv2D:
            filters: 64
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 64
            kernel_size: 3
            padding: same
            activation: relu
        - MaxPooling2D:
            pool_size: 2
            strides: 2
            padding: same
        - Conv2D:
            filters: 128
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 128
            kernel_size: 3
            padding: same
            activation: relu
        - MaxPooling2D:
            pool_size: 2
            strides: 2
            padding: same
        - Conv2D:
            filters: 256
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 256
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 256
            kernel_size: 3
            padding: same
            activation: relu
        - MaxPooling2D:
            pool_size: 2
            strides: 2
            padding: same
        - Conv2D:
            filters: 512
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 512
            kernel_size: 3
            padding: same
            activation: relu
        - Conv2D:
            filters: 512
            kernel_size: 3
            padding: same
            activation: relu
        - MaxPooling2D:
            pool_size: 2
            strides: 2
            padding: same
        - Flatten:
        - Dense:
            units: 4096
            activation: relu
            dropout: 0.5
        - Dense:
            units: 4096
            activation: relu
            dropout: 0.5
        - Dense:
            units: 10

train:
  train_steps: 100
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 64
      num_epochs: 5
      shuffle: true
      data_files: ["../data/mnist/mnist_train.tfrecord"]
      meta_data_file: "../data/mnist/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32

eval:
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 32
      num_epochs: 1
      shuffle: False
      data_files: ["../data/mnist/mnist_eval.tfrecord"]
      meta_data_file: "../data/mnist/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32
