export enum actionTypes {
  DELETE_NOTEBOOK_REQUEST = 'DELETE_NOTEBOOK_REQUEST',
  DELETE_NOTEBOOK_SUCCESS = 'DELETE_NOTEBOOK_SUCCESS',
  DELETE_NOTEBOOK_ERROR = 'DELETE_NOTEBOOK_ERROR',

  STOP_NOTEBOOK_REQUEST = 'STOP_NOTEBOOK_REQUEST',
  STOP_NOTEBOOK_SUCCESS = 'STOP_NOTEBOOK_SUCCESS',
  STOP_NOTEBOOK_ERROR = 'STOP_NOTEBOOK_ERROR',

  ARCHIVE_NOTEBOOK_REQUEST = 'ARCHIVE_NOTEBOOK_REQUEST',
  ARCHIVE_NOTEBOOK_SUCCESS = 'ARCHIVE_NOTEBOOK_SUCCESS',
  ARCHIVE_NOTEBOOK_ERROR = 'ARCHIVE_NOTEBOOK_ERROR',

  RESTORE_NOTEBOOK_REQUEST = 'RESTORE_NOTEBOOK_REQUEST',
  RESTORE_NOTEBOOK_SUCCESS = 'RESTORE_NOTEBOOK_SUCCESS',
  RESTORE_NOTEBOOK_ERROR = 'RESTORE_NOTEBOOK_ERROR',

  UPDATE_NOTEBOOK_REQUEST = 'UPDATE_NOTEBOOK_REQUEST',
  UPDATE_NOTEBOOK_SUCCESS = 'UPDATE_NOTEBOOK_SUCCESS',
  UPDATE_NOTEBOOK_ERROR = 'UPDATE_NOTEBOOK_ERROR',

  GET_NOTEBOOK_REQUEST = 'GET_NOTEBOOK_REQUEST',
  GET_NOTEBOOK_SUCCESS = 'GET_NOTEBOOK_SUCCESS',
  GET_NOTEBOOK_ERROR = 'GET_NOTEBOOK_ERROR',

  FETCH_NOTEBOOKS_REQUEST = 'FETCH_NOTEBOOKS_REQUEST',
  FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS',
  FETCH_NOTEBOOKS_ERROR = 'FETCH_NOTEBOOKS_ERROR',

  BOOKMARK_NOTEBOOK_REQUEST = 'BOOKMARK_NOTEBOOK_REQUEST',
  BOOKMARK_NOTEBOOK_SUCCESS = 'BOOKMARK_NOTEBOOK_SUCCESS',
  BOOKMARK_NOTEBOOK_ERROR = 'BOOKMARK_NOTEBOOK_ERROR',

  UNBOOKMARK_NOTEBOOK_REQUEST = 'UNBOOKMARK_NOTEBOOK_REQUEST',
  UNBOOKMARK_NOTEBOOK_SUCCESS = 'UNBOOKMARK_NOTEBOOK_SUCCESS',
  UNBOOKMARK_NOTEBOOK_ERROR = 'UNBOOKMARK_NOTEBOOK_ERROR',
}
