import auditor

from event_manager.events import notebook

auditor.subscribe(notebook.NotebookStartedEvent)
auditor.subscribe(notebook.NotebookStartedTriggeredEvent)
auditor.subscribe(notebook.NotebookSoppedEvent)
auditor.subscribe(notebook.NotebookSoppedTriggeredEvent)
auditor.subscribe(notebook.NotebookCleanedTriggeredEvent)
auditor.subscribe(notebook.NotebookViewedEvent)
auditor.subscribe(notebook.NotebookNewStatusEvent)
auditor.subscribe(notebook.NotebookFailedEvent)
auditor.subscribe(notebook.NotebookSucceededEvent)
auditor.subscribe(notebook.NotebookUpdatedEvent)
auditor.subscribe(notebook.NotebookDeletedEvent)
auditor.subscribe(notebook.NotebookDeletedTriggeredEvent)
auditor.subscribe(notebook.NotebookStatusesViewedEvent)
auditor.subscribe(notebook.NotebookArchivedEvent)
auditor.subscribe(notebook.NotebookRestoredEvent)
