// Copyright 2018-2020 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package hub_models_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHubModelParams creates a new GetHubModelParams object
// with the default values initialized.
func NewGetHubModelParams() *GetHubModelParams {
	var ()
	return &GetHubModelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHubModelParamsWithTimeout creates a new GetHubModelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHubModelParamsWithTimeout(timeout time.Duration) *GetHubModelParams {
	var ()
	return &GetHubModelParams{

		timeout: timeout,
	}
}

// NewGetHubModelParamsWithContext creates a new GetHubModelParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHubModelParamsWithContext(ctx context.Context) *GetHubModelParams {
	var ()
	return &GetHubModelParams{

		Context: ctx,
	}
}

// NewGetHubModelParamsWithHTTPClient creates a new GetHubModelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHubModelParamsWithHTTPClient(client *http.Client) *GetHubModelParams {
	var ()
	return &GetHubModelParams{
		HTTPClient: client,
	}
}

/*GetHubModelParams contains all the parameters to send to the API endpoint
for the get hub model operation typically these are written to a http.Request
*/
type GetHubModelParams struct {

	/*Owner
	  Owner of the namespace

	*/
	Owner string
	/*UUID
	  Uuid identifier of the entity

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hub model params
func (o *GetHubModelParams) WithTimeout(timeout time.Duration) *GetHubModelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hub model params
func (o *GetHubModelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hub model params
func (o *GetHubModelParams) WithContext(ctx context.Context) *GetHubModelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hub model params
func (o *GetHubModelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hub model params
func (o *GetHubModelParams) WithHTTPClient(client *http.Client) *GetHubModelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hub model params
func (o *GetHubModelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the get hub model params
func (o *GetHubModelParams) WithOwner(owner string) *GetHubModelParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get hub model params
func (o *GetHubModelParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithUUID adds the uuid to the get hub model params
func (o *GetHubModelParams) WithUUID(uuid string) *GetHubModelParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get hub model params
func (o *GetHubModelParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetHubModelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
