export enum actionTypes {
  CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST',
  CREATE_JOB_ERROR = 'CREATE_JOB_ERROR',

  DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST',
  DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS',
  DELETE_JOB_ERROR = 'DELETE_JOB_ERROR',

  STOP_JOB_REQUEST = 'STOP_JOB_REQUEST',
  STOP_JOB_SUCCESS = 'STOP_JOB_SUCCESS',
  STOP_JOB_ERROR = 'STOP_JOB_ERROR',

  ARCHIVE_JOB_REQUEST = 'ARCHIVE_JOB_REQUEST',
  ARCHIVE_JOB_SUCCESS = 'ARCHIVE_JOB_SUCCESS',
  ARCHIVE_JOB_ERROR = 'ARCHIVE_JOB_ERROR',

  RESTORE_JOB_REQUEST = 'RESTORE_JOB_REQUEST',
  RESTORE_JOB_SUCCESS = 'RESTORE_JOB_SUCCESS',
  RESTORE_JOB_ERROR = 'RESTORE_JOB_ERROR',

  UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST',
  UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS',
  UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR',

  GET_JOB_REQUEST = 'GET_JOB_REQUEST',
  GET_JOB_SUCCESS = 'GET_JOB_SUCCESS',
  GET_JOB_ERROR = 'GET_JOB_ERROR',

  FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST',
  FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR',

  BOOKMARK_JOB_REQUEST = 'BOOKMARK_JOB_REQUEST',
  BOOKMARK_JOB_SUCCESS = 'BOOKMARK_JOB_SUCCESS',
  BOOKMARK_JOB_ERROR = 'BOOKMARK_JOB_ERROR',

  UNBOOKMARK_JOB_REQUEST = 'UNBOOKMARK_JOB_REQUEST',
  UNBOOKMARK_JOB_SUCCESS = 'UNBOOKMARK_JOB_SUCCESS',
  UNBOOKMARK_JOB_ERROR = 'UNBOOKMARK_JOB_ERROR',
}
