export enum actionTypes {
  CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST',
  CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR',

  DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST',
  DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS',
  DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR',

  STOP_GROUP_REQUEST = 'STOP_GROUP_REQUEST',
  STOP_GROUP_SUCCESS = 'STOP_GROUP_SUCCESS',
  STOP_GROUP_ERROR = 'STOP_GROUP_ERROR',

  ARCHIVE_GROUP_REQUEST = 'ARCHIVE_GROUP_REQUEST',
  ARCHIVE_GROUP_SUCCESS = 'ARCHIVE_GROUP_SUCCESS',
  ARCHIVE_GROUP_ERROR = 'ARCHIVE_GROUP_ERROR',

  RESTORE_GROUP_REQUEST = 'RESTORE_GROUP_REQUEST',
  RESTORE_GROUP_SUCCESS = 'RESTORE_GROUP_SUCCESS',
  RESTORE_GROUP_ERROR = 'RESTORE_GROUP_ERROR',

  UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST',
  UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS',
  UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR',

  GET_GROUP_REQUEST = 'GET_GROUP_REQUEST',
  GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS',
  GET_GROUP_ERROR = 'GET_GROUP_ERROR',

  FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST',
  FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS',
  FETCH_GROUPS_ERROR = 'FETCH_GROUPS_ERROR',

  BOOKMARK_GROUP_REQUEST = 'BOOKMARK_GROUP_REQUEST',
  BOOKMARK_GROUP_SUCCESS = 'BOOKMARK_GROUP_SUCCESS',
  BOOKMARK_GROUP_ERROR = 'BOOKMARK_GROUP_ERROR',

  UNBOOKMARK_GROUP_REQUEST = 'UNBOOKMARK_GROUP_REQUEST',
  UNBOOKMARK_GROUP_SUCCESS = 'UNBOOKMARK_GROUP_SUCCESS',
  UNBOOKMARK_GROUP_ERROR = 'UNBOOKMARK_GROUP_ERROR',

  START_GROUP_TENSORBOARD_REQUEST = 'START_GROUP_TENSORBOARD_REQUEST',
  START_GROUP_TENSORBOARD_SUCCESS = 'START_GROUP_TENSORBOARD_SUCCESS',
  START_GROUP_TENSORBOARD_ERROR = 'START_GROUP_TENSORBOARD_ERROR',

  STOP_GROUP_TENSORBOARD_REQUEST = 'STOP_GROUP_TENSORBOARD_REQUEST',
  STOP_GROUP_TENSORBOARD_SUCCESS = 'STOP_GROUP_TENSORBOARD_SUCCESS',
  STOP_GROUP_TENSORBOARD_ERROR = 'STOP_GROUP_TENSORBOARD_ERROR',
}
