// Copyright 2018-2021 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package component_hub_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// GetComponentHubActivitiesReader is a Reader for the GetComponentHubActivities structure.
type GetComponentHubActivitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComponentHubActivitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComponentHubActivitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetComponentHubActivitiesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetComponentHubActivitiesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetComponentHubActivitiesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetComponentHubActivitiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetComponentHubActivitiesOK creates a GetComponentHubActivitiesOK with default headers values
func NewGetComponentHubActivitiesOK() *GetComponentHubActivitiesOK {
	return &GetComponentHubActivitiesOK{}
}

/* GetComponentHubActivitiesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetComponentHubActivitiesOK struct {
	Payload *service_model.V1ListActivitiesResponse
}

func (o *GetComponentHubActivitiesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/{owner}/hub/{name}/activities][%d] getComponentHubActivitiesOK  %+v", 200, o.Payload)
}
func (o *GetComponentHubActivitiesOK) GetPayload() *service_model.V1ListActivitiesResponse {
	return o.Payload
}

func (o *GetComponentHubActivitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1ListActivitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentHubActivitiesNoContent creates a GetComponentHubActivitiesNoContent with default headers values
func NewGetComponentHubActivitiesNoContent() *GetComponentHubActivitiesNoContent {
	return &GetComponentHubActivitiesNoContent{}
}

/* GetComponentHubActivitiesNoContent describes a response with status code 204, with default header values.

No content.
*/
type GetComponentHubActivitiesNoContent struct {
	Payload interface{}
}

func (o *GetComponentHubActivitiesNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/{owner}/hub/{name}/activities][%d] getComponentHubActivitiesNoContent  %+v", 204, o.Payload)
}
func (o *GetComponentHubActivitiesNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *GetComponentHubActivitiesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentHubActivitiesForbidden creates a GetComponentHubActivitiesForbidden with default headers values
func NewGetComponentHubActivitiesForbidden() *GetComponentHubActivitiesForbidden {
	return &GetComponentHubActivitiesForbidden{}
}

/* GetComponentHubActivitiesForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type GetComponentHubActivitiesForbidden struct {
	Payload interface{}
}

func (o *GetComponentHubActivitiesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/{owner}/hub/{name}/activities][%d] getComponentHubActivitiesForbidden  %+v", 403, o.Payload)
}
func (o *GetComponentHubActivitiesForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *GetComponentHubActivitiesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentHubActivitiesNotFound creates a GetComponentHubActivitiesNotFound with default headers values
func NewGetComponentHubActivitiesNotFound() *GetComponentHubActivitiesNotFound {
	return &GetComponentHubActivitiesNotFound{}
}

/* GetComponentHubActivitiesNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type GetComponentHubActivitiesNotFound struct {
	Payload interface{}
}

func (o *GetComponentHubActivitiesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/{owner}/hub/{name}/activities][%d] getComponentHubActivitiesNotFound  %+v", 404, o.Payload)
}
func (o *GetComponentHubActivitiesNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetComponentHubActivitiesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentHubActivitiesDefault creates a GetComponentHubActivitiesDefault with default headers values
func NewGetComponentHubActivitiesDefault(code int) *GetComponentHubActivitiesDefault {
	return &GetComponentHubActivitiesDefault{
		_statusCode: code,
	}
}

/* GetComponentHubActivitiesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetComponentHubActivitiesDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// Code gets the status code for the get component hub activities default response
func (o *GetComponentHubActivitiesDefault) Code() int {
	return o._statusCode
}

func (o *GetComponentHubActivitiesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/{owner}/hub/{name}/activities][%d] GetComponentHubActivities default  %+v", o._statusCode, o.Payload)
}
func (o *GetComponentHubActivitiesDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *GetComponentHubActivitiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
