export enum actionTypes {
  CREATE_BUILD_REQUEST = 'CREATE_BUILD_REQUEST',
  CREATE_BUILD_ERROR = 'CREATE_BUILD_ERROR',
  CREATE_BUILD_SUCCESS = 'CREATE_BUILD_SUCCESS',

  DELETE_BUILD_REQUEST = 'DELETE_BUILD_REQUEST',
  DELETE_BUILD_SUCCESS = 'DELETE_BUILD_SUCCESS',
  DELETE_BUILD_ERROR = 'DELETE_BUILD_ERROR',

  STOP_BUILD_REQUEST = 'STOP_BUILD_REQUEST',
  STOP_BUILD_SUCCESS = 'STOP_BUILD_SUCCESS',
  STOP_BUILD_ERROR = 'STOP_BUILD_ERROR',

  ARCHIVE_BUILD_REQUEST = 'ARCHIVE_BUILD_REQUEST',
  ARCHIVE_BUILD_SUCCESS = 'ARCHIVE_BUILD_SUCCESS',
  ARCHIVE_BUILD_ERROR = 'ARCHIVE_BUILD_ERROR',

  RESTORE_BUILD_REQUEST = 'RESTORE_BUILD_REQUEST',
  RESTORE_BUILD_SUCCESS = 'RESTORE_BUILD_SUCCESS',
  RESTORE_BUILD_ERROR = 'RESTORE_BUILD_ERROR',

  UPDATE_BUILD_REQUEST = 'UPDATE_BUILD_REQUEST',
  UPDATE_BUILD_SUCCESS = 'UPDATE_BUILD_SUCCESS',
  UPDATE_BUILD_ERROR = 'UPDATE_BUILD_ERROR',

  GET_BUILD_REQUEST = 'GET_BUILD_REQUEST',
  GET_BUILD_SUCCESS = 'GET_BUILD_SUCCESS',
  GET_BUILD_ERROR = 'GET_BUILD_ERROR',

  FETCH_BUILDS_REQUEST = 'FETCH_BUILDS_REQUEST',
  FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS',
  FETCH_BUILDS_ERROR = 'FETCH_BUILDS_ERROR',

  BOOKMARK_BUILD_REQUEST = 'BOOKMARK_BUILD_REQUEST',
  BOOKMARK_BUILD_SUCCESS = 'BOOKMARK_BUILD_SUCCESS',
  BOOKMARK_BUILD_ERROR = 'BOOKMARK_BUILD_ERROR',

  UNBOOKMARK_BUILD_REQUEST = 'UNBOOKMARK_BUILD_REQUEST',
  UNBOOKMARK_BUILD_SUCCESS = 'UNBOOKMARK_BUILD_SUCCESS',
  UNBOOKMARK_BUILD_ERROR = 'UNBOOKMARK_BUILD_ERROR',
}
