export enum actionTypes {
  FETCH_CHART_VIEWS_REQUEST = 'FETCH_CHART_VIEWS_REQUEST',
  FETCH_CHART_VIEWS_SUCCESS = 'FETCH_CHART_VIEWS_SUCCESS',
  FETCH_CHART_VIEWS_ERROR = 'FETCH_CHART_VIEWS_ERROR',

  GET_CHART_VIEW_REQUEST = 'GET_CHART_VIEW_REQUEST',
  GET_CHART_VIEW_SUCCESS = 'GET_CHART_VIEW_SUCCESS',
  GET_CHART_VIEW_ERROR = 'GET_CHART_VIEW_ERROR',

  CREATE_CHART_VIEW_REQUEST = 'CREATE_CHART_VIEW_REQUEST',
  CREATE_CHART_VIEW_SUCCESS = 'CREATE_CHART_VIEW_SUCCESS',
  CREATE_CHART_VIEW_ERROR = 'CREATE_CHART_VIEW_ERROR',

  DELETE_CHART_VIEW_REQUEST = 'DELETE_CHART_VIEW_REQUEST',
  DELETE_CHART_VIEW_SUCCESS = 'DELETE_CHART_VIEW_SUCCESS',
  DELETE_CHART_VIEW_ERROR = 'DELETE_CHART_VIEW_ERROR',
}
