NAME = 'polyaxon-cli'
VERSION = '0.5.2'
DESC = 'Command Line Interface (CLI) for Polyaxon.'
URL = 'https://github.com/polyaxon/polyaxon-cli'
AUTHOR = 'Mourad Mourafiq'
EMAIL = 'mourad@polyaxon.com'
LICENSE = 'MIT'
