import analytics
from event_manager.events import permission

analytics.subscribe(permission.PermissionProjectDeniedEvent)
analytics.subscribe(permission.PermissionRepoDeniedEvent)
analytics.subscribe(permission.PermissionExperimentGroupDeniedEvent)
analytics.subscribe(permission.PermissionExperimentDeniedEvent)
analytics.subscribe(permission.PermissionTensorboardDeniedEvent)
analytics.subscribe(permission.PermissionNotebookDeniedEvent)
analytics.subscribe(permission.PermissionExperimentJobDeniedEvent)
analytics.subscribe(permission.PermissionClusterDeniedEvent)
analytics.subscribe(permission.PermissionUserRoleEvent)
