import analytics
from event_manager.events import tensorboard

analytics.register(tensorboard.TensorboardStartedEvent)
analytics.register(tensorboard.TensorboardSoppedEvent)
analytics.register(tensorboard.TensorboardViewedEvent)
analytics.register(tensorboard.TensorboardNewStatusEvent)
