#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
    echo "========================"
    echo "Helm agent"
    echo "========================"
    $DIR/helm/agent
    echo "========================"
    echo "Helm platform"
    echo "========================"
    $DIR/helm/platform
fi
