#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
    echo "Init templates"
    rm -r charts/polyaxon/templates/*
    mkdir charts/polyaxon/templates/partials
    mkdir charts/polyaxon/templates/hooks
    mkdir charts/polyaxon/templates/metrics
    mkdir charts/polyaxon/templates/tests
    mkdir charts/polyaxon/templates/crds

    echo "Copy ignore and notes"
    cp helm/templates/.helmignore charts/polyaxon/.helmignore
    cp helm/templates/NOTES.txt charts/polyaxon/templates/NOTES.txt

    echo "Copy crds"
    cp -r helm/templates/agent/crds/* charts/polyaxon/templates/crds/

    echo "Copy hooks"
    cp -r helm/templates/common/hooks/* charts/polyaxon/templates/hooks/
    cp -r helm/templates/platform/hooks/* charts/polyaxon/templates/hooks/
    cp -r helm/templates/scheduler/hooks/* charts/polyaxon/templates/hooks/

    echo "Copy tests"
    cp -r helm/templates/platform/tests/* charts/polyaxon/templates/tests/

    echo "Copy metrics"
    cp -r helm/templates/platform/metrics/* charts/polyaxon/templates/metrics/

    echo "Copy partials"
    cp -r helm/templates/agent/partials/* charts/polyaxon/templates/partials/
    cp -r helm/templates/common/partials/* charts/polyaxon/templates/partials/
    cp -r helm/templates/platform/partials/* charts/polyaxon/templates/partials/
    cp -r helm/templates/scheduler/partials/* charts/polyaxon/templates/partials/

    echo "Copy agent templates"
    cp -r helm/templates/agent/* charts/polyaxon/templates/
    echo "Copy common templates"
    cp -r helm/templates/common/* charts/polyaxon/templates/
    echo "Copy platform templates"
    cp -r helm/templates/platform/* charts/polyaxon/templates/
    cp -r helm/templates/scheduler/* charts/polyaxon/templates/
fi
