# Generated by Django 2.0.8 on 2018-09-05 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_experimentjob_tolerations_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereference',
            name='branch',
            field=models.CharField(blank=True, default='master', max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='codereference',
            name='git_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='codereference',
            name='head',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='codereference',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='run_env',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'in_cluster': True}, help_text='The run environment of the experiment.', null=True),
        ),
    ]
