# Generated by Django 2.1.3 on 2018-12-17 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import libs.resource_validation


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_experimentjob_sequence_and_deleted_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresources',
            name='tpu',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[libs.resource_validation.validate_resource]),
        ),
    ]
