export enum actionTypes {
  CREATE_ACCESS_REQUEST = 'CREATE_ACCESS_REQUEST',
  CREATE_ACCESS_SUCCESS = 'CREATE_ACCESS_SUCCESS',
  CREATE_ACCESS_ERROR = 'CREATE_ACCESS_ERROR',

  DELETE_ACCESS_REQUEST = 'DELETE_ACCESS_REQUEST',
  DELETE_ACCESS_SUCCESS = 'DELETE_ACCESS_SUCCESS',
  DELETE_ACCESS_ERROR = 'DELETE_ACCESS_ERROR',

  UPDATE_ACCESS_REQUEST = 'UPDATE_ACCESS_REQUEST',
  UPDATE_ACCESS_SUCCESS = 'UPDATE_ACCESS_SUCCESS',
  UPDATE_ACCESS_ERROR = 'UPDATE_ACCESS_ERROR',

  GET_ACCESS_REQUEST = 'GET_ACCESS_REQUEST',
  GET_ACCESS_SUCCESS = 'GET_ACCESS_SUCCESS',
  GET_ACCESS_ERROR = 'GET_ACCESS_ERROR',

  FETCH_ACCESSES_REQUEST = 'FETCH_ACCESSES_REQUEST',
  FETCH_ACCESSES_SUCCESS = 'FETCH_ACCESSES_SUCCESS',
  FETCH_ACCESSES_ERROR = 'FETCH_ACCESSES_ERROR',

  INIT_ACCESS_REQUEST = 'INIT_ACCESS_REQUEST',
}
