// Copyright 2019 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package k8s_secrets_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteK8sSecretParams creates a new DeleteK8sSecretParams object
// with the default values initialized.
func NewDeleteK8sSecretParams() *DeleteK8sSecretParams {
	var ()
	return &DeleteK8sSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteK8sSecretParamsWithTimeout creates a new DeleteK8sSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteK8sSecretParamsWithTimeout(timeout time.Duration) *DeleteK8sSecretParams {
	var ()
	return &DeleteK8sSecretParams{

		timeout: timeout,
	}
}

// NewDeleteK8sSecretParamsWithContext creates a new DeleteK8sSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteK8sSecretParamsWithContext(ctx context.Context) *DeleteK8sSecretParams {
	var ()
	return &DeleteK8sSecretParams{

		Context: ctx,
	}
}

// NewDeleteK8sSecretParamsWithHTTPClient creates a new DeleteK8sSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteK8sSecretParamsWithHTTPClient(client *http.Client) *DeleteK8sSecretParams {
	var ()
	return &DeleteK8sSecretParams{
		HTTPClient: client,
	}
}

/*DeleteK8sSecretParams contains all the parameters to send to the API endpoint
for the delete k8s secret operation typically these are written to a http.Request
*/
type DeleteK8sSecretParams struct {

	/*Owner
	  Owner of the namespace

	*/
	Owner string
	/*UUID
	  Unique integer identifier of the entity

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete k8s secret params
func (o *DeleteK8sSecretParams) WithTimeout(timeout time.Duration) *DeleteK8sSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete k8s secret params
func (o *DeleteK8sSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete k8s secret params
func (o *DeleteK8sSecretParams) WithContext(ctx context.Context) *DeleteK8sSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete k8s secret params
func (o *DeleteK8sSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete k8s secret params
func (o *DeleteK8sSecretParams) WithHTTPClient(client *http.Client) *DeleteK8sSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete k8s secret params
func (o *DeleteK8sSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the delete k8s secret params
func (o *DeleteK8sSecretParams) WithOwner(owner string) *DeleteK8sSecretParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete k8s secret params
func (o *DeleteK8sSecretParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithUUID adds the uuid to the delete k8s secret params
func (o *DeleteK8sSecretParams) WithUUID(uuid string) *DeleteK8sSecretParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete k8s secret params
func (o *DeleteK8sSecretParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteK8sSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
