// Copyright 2018-2021 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* tslint:disable */
/* eslint-disable */
/**
 * Polyaxon SDKs and REST API specification.
 * Polyaxon SDKs and REST API specification.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: contact@polyaxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PolyaxonSidecarContainer
 */
export interface V1PolyaxonSidecarContainer {
    /**
     * 
     * @type {string}
     * @memberof V1PolyaxonSidecarContainer
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PolyaxonSidecarContainer
     */
    image_tag?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PolyaxonSidecarContainer
     */
    image_pull_policy?: string;
    /**
     * 
     * @type {number}
     * @memberof V1PolyaxonSidecarContainer
     */
    sleep_interval?: number;
    /**
     * 
     * @type {number}
     * @memberof V1PolyaxonSidecarContainer
     */
    sync_interval?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1PolyaxonSidecarContainer
     */
    monitor_logs?: boolean;
    /**
     * 
     * @type {object}
     * @memberof V1PolyaxonSidecarContainer
     */
    resources?: object;
}

export function V1PolyaxonSidecarContainerFromJSON(json: any): V1PolyaxonSidecarContainer {
    return V1PolyaxonSidecarContainerFromJSONTyped(json, false);
}

export function V1PolyaxonSidecarContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PolyaxonSidecarContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
        'image_tag': !exists(json, 'image_tag') ? undefined : json['image_tag'],
        'image_pull_policy': !exists(json, 'image_pull_policy') ? undefined : json['image_pull_policy'],
        'sleep_interval': !exists(json, 'sleep_interval') ? undefined : json['sleep_interval'],
        'sync_interval': !exists(json, 'sync_interval') ? undefined : json['sync_interval'],
        'monitor_logs': !exists(json, 'monitor_logs') ? undefined : json['monitor_logs'],
        'resources': !exists(json, 'resources') ? undefined : json['resources'],
    };
}

export function V1PolyaxonSidecarContainerToJSON(value?: V1PolyaxonSidecarContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'image_tag': value.image_tag,
        'image_pull_policy': value.image_pull_policy,
        'sleep_interval': value.sleep_interval,
        'sync_interval': value.sync_interval,
        'monitor_logs': value.monitor_logs,
        'resources': value.resources,
    };
}


