from polyaxon.config_settings.admin import *
from polyaxon.config_settings.assets import *
from polyaxon.config_settings.auth import *
from polyaxon.config_settings.cors import *
from polyaxon.config_settings.dirs import *
from polyaxon.config_settings.email import *
from polyaxon.config_settings.k8s import *
from polyaxon.config_settings.middlewares import *
from polyaxon.config_settings.registration import *
from polyaxon.config_settings.rest import *
from polyaxon.config_settings.spawner import *
from polyaxon.config_settings.volume_claims import *
from .apps import *
