dependencies:
  - name: postgresql
    version: 0.8.7
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: 0.6.15
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 1.1.7
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: docker-registry
    version: 1.0.1
    repository: https://kubernetes-charts.storage.googleapis.com/
