#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
    QUEUES="$(./worker/queues.sh ./worker/queues/worker $*)"
    docker-compose run --rm --name=polyaxon_worker web /bin/bash ./worker/start.sh worker --without-mingle --without-gossip --loglevel=DEBUG -Q $QUEUES --concurrency=4 -n default@%h
fi
