#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
    if [ -z "$1" ]; then
        QUEUES="queues.pipelines"
    else
        QUEUES=$*
    fi
    docker-compose run -w /polyaxon/polyaxon --rm --name=polyaxon_worker web celery -A polyaxon worker --without-mingle --without-gossip --loglevel=DEBUG -Q $QUEUES --concurrency=4 -n default@%h
fi
