#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose run --rm --name=polyaxon_beat web /bin/bash ./worker/start.sh beat --loglevel=DEBUG
fi
