#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose run -w /polyaxon/polyaxon --rm --name=polyaxon_beat web celery -A polyaxon beat --loglevel=DEBUG
fi
