#!/usr/bin/env bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

echo "Cleaning..."
source $DIR/clean

docker stop $(docker ps -q -a)
docker rm $(docker ps -q -a)
docker rmi -f $(docker images -q -a)
docker network rm $(docker network ls -q)
