#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose -f docker-compose.yml -f docker-compose.testing.yml down
    docker-compose down
fi
