#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    containers=$(docker ps -a -q --filter=ancestor=plx)
    [ -n "$containers" ] && docker rm $containers
    docker rmi plx
fi
