#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    $DIR/manage dumpdata --indent 4 --natural-primary --natural-foreign $* > polyaxon/fixtures/$*.json
fi
