#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose -p web-testing -f docker-compose.yml -f docker-compose.testing.yml run web isort -rc .
fi
