#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose run -w /polyaxon/client --rm --name=polyaxon_npm web npm $*
fi
