#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose -p web-testing -f docker-compose.yml -f docker-compose.testing.yml run web isort -rc --check-only .
    docker-compose -p web-testing -f docker-compose.yml -f docker-compose.testing.yml run --no-deps web prospector -X polyaxon
    docker-compose -p web-testing -f docker-compose.yml -f docker-compose.testing.yml run --no-deps web prospector -X tests
    docker-compose -p web-testing -f docker-compose.yml -f docker-compose.testing.yml run web python3 polyaxon/manage.py check
fi
