#!/bin/bash
if [ $? -eq 0 ]; then
    echo "========================"
    echo "pull npm base"
    echo "========================"
    docker pull polyaxon/polyaxon-npm-base
    echo "========================"
    echo "build base dev"
    echo "========================"
    docker build -f platform/base/Dockerfile.dev -t polyaxon-base-dev .
    echo "========================"
    echo "build api"
    echo "========================"
    docker-compose build api $*
    echo "========================"
fi
