#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose run -w /polyaxon/api --rm --name=polyaxon_redis redis redis-cli -h redis
fi
