#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    docker-compose run --publish 8000:8000 --rm --name=polyaxon-web web python3 ./api/manage.py runserver 0.0.0.0:8000
fi
