#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    # Does not expose any ports, so you can use the runserver at the same time.
    docker-compose run --publish 1337:1337 -w /polyaxon/polyaxon --rm --name=polyaxon_sanic web python3 -m sanic events_monitors.api.app --host=0.0.0.0 --port=1337 --workers=1
fi
