#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
    docker-compose run -w /polyaxon/polyaxon/sidecar --rm --name=polyaxon_sidecar web python3 sidecar/__main__.py
fi
