#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
     docker-compose run -w /polyaxon-api/tensor-logs -p 6006:6006 --rm --name=polyaxon_tensorboard web tensorboard --logdir=${PWD} --host=0.0.0.0
fi
