#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

if [ $? -eq 0 ]; then
     docker run -v $dir/..:/  -w /polyaxon/examples/polyaxon-logs -p 6006:6006 --rm --name=polyaxon_tensorboard plx tensorboard --logdir=${PWD} --host=0.0.0.0
fi
