#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

PYTESTOPT="-v"

if [ $? -eq 0 ]; then
    docker run -v $DIR/..:/polyaxon plx py.test $PYTESTOPT $*
fi
