#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/environment

$DIR/check

if grep -q DATABASE_URL docker-compose.yml ; then
    PYTESTOPT="--reuse-db -v"
else
    PYTESTOPT="-v"
fi

if [ $? -eq 0 ]; then
    docker-compose -p plx_testing -f docker-compose.yml -f docker-compose.testing.yml run plx py.test $PYTESTOPT $*
fi
