import conf

from options.registry import container_names

conf.subscribe(container_names.ContainerNameBuildJobs)
conf.subscribe(container_names.ContainerNameExperimentJobs)
conf.subscribe(container_names.ContainerNameJobs)
conf.subscribe(container_names.ContainerNameTFJobs)
conf.subscribe(container_names.ContainerNamePytorchJobs)
conf.subscribe(container_names.ContainerNameSidecars)
conf.subscribe(container_names.ContainerNameInit)
conf.subscribe(container_names.ContainerNamePluginJobs)
