from polyaxon.config_settings.assets import *
from polyaxon.config_settings.auth import *
from polyaxon.config_settings.context_processors import *
from polyaxon.config_settings.cors import *
from polyaxon.config_settings.email import *
from polyaxon.config_settings.k8s import *
from polyaxon.config_settings.notification_urls import *
from polyaxon.config_settings.oauth import *
from polyaxon.config_settings.paths import *
from polyaxon.config_settings.redis_settings import *
from polyaxon.config_settings.registration import *
from polyaxon.config_settings.registry import *
from polyaxon.config_settings.rest import *
from polyaxon.config_settings.spawner import *
from polyaxon.config_settings.volume_claims import *
from polyaxon.config_settings.middlewares import *
from .apps import *
