export enum actionTypes {
  CREATE_SEARCH_REQUEST = 'CREATE_SEARCH_REQUEST',
  CREATE_SEARCH_ERROR = 'CREATE_SEARCH_ERROR',
  CREATE_SEARCH_SUCCESS = 'CREATE_SEARCH_SUCCESS',

  DELETE_SEARCH_REQUEST = 'DELETE_SEARCH_REQUEST',
  DELETE_SEARCH_SUCCESS = 'DELETE_SEARCH_SUCCESS',
  DELETE_SEARCH_ERROR = 'DELETE_SEARCH_ERROR',

  GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS',

  FETCH_SEARCHES_REQUEST = 'FETCH_SEARCHES_REQUEST',
  FETCH_SEARCHES_SUCCESS = 'FETCH_SEARCHES_SUCCESS',
  FETCH_SEARCHES_ERROR = 'FETCH_SEARCHES_ERROR',
}
