#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

PACKAGE_PATH=$1

$DIR/check
if [ $? -eq 0 ]; then
    cmd/python/api platform/coreapi polyaxon/manage.py $*
fi
