#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    cmd/python/scheduler platform/core-scheduler polyaxon/manage.py $*
fi
