import tracker

from event_manager.events import bookmark

tracker.subscribe(bookmark.BookmarkBuildJobsViewedEvent)
tracker.subscribe(bookmark.BookmarkJobsViewedEvent)
tracker.subscribe(bookmark.BookmarkExperimentsViewedEvent)
tracker.subscribe(bookmark.BookmarkExperimentGroupsViewedEvent)
tracker.subscribe(bookmark.BookmarkProjectsViewedEvent)
