import tracker

from event_manager.events import operation_run

tracker.subscribe(operation_run.OperationRunCreatedEvent)
tracker.subscribe(operation_run.OperationRunUpdatedEvent)
tracker.subscribe(operation_run.OperationRunCleanedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunViewedEvent)
tracker.subscribe(operation_run.OperationRunArchivedEvent)
tracker.subscribe(operation_run.OperationRunRestoredEvent)
tracker.subscribe(operation_run.OperationRunSkippedEvent)
tracker.subscribe(operation_run.OperationRunDeletedEvent)
tracker.subscribe(operation_run.OperationRunDeletedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunStoppedEvent)
tracker.subscribe(operation_run.OperationRunStoppedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunResumedEvent)
tracker.subscribe(operation_run.OperationRunResumedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunRestartedEvent)
tracker.subscribe(operation_run.OperationRunRestartedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunSkippedTriggeredEvent)
tracker.subscribe(operation_run.OperationRunNewStatusEvent)
tracker.subscribe(operation_run.OperationRunSucceededEvent)
tracker.subscribe(operation_run.OperationRunFailedEvent)
tracker.subscribe(operation_run.OperationRunDoneEvent)
