import tracker

from events.registry import tensorboard

tracker.subscribe(tensorboard.TensorboardStartedEvent)
tracker.subscribe(tensorboard.TensorboardStartedTriggeredEvent)
tracker.subscribe(tensorboard.TensorboardSoppedEvent)
tracker.subscribe(tensorboard.TensorboardSoppedTriggeredEvent)
tracker.subscribe(tensorboard.TensorboardViewedEvent)
tracker.subscribe(tensorboard.TensorboardUpdatedEvent)
tracker.subscribe(tensorboard.TensorboardDeletedEvent)
tracker.subscribe(tensorboard.TensorboardDeletedTriggeredEvent)
tracker.subscribe(tensorboard.TensorboardBookmarkedEvent)
tracker.subscribe(tensorboard.TensorboardUnBookmarkedEvent)
tracker.subscribe(tensorboard.TensorboardNewStatusEvent)
tracker.subscribe(tensorboard.TensorboardSucceededEvent)
tracker.subscribe(tensorboard.TensorboardFailedEvent)
tracker.subscribe(tensorboard.TensorboardStatusesViewedEvent)
tracker.subscribe(tensorboard.TensorboardArchivedEvent)
tracker.subscribe(tensorboard.TensorboardRestoredEvent)
