#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

if [ $# -lt 1 ]
  then
    echo "You should provide at least 1 args: path"
    exit 1
fi

$DIR/check

PACKAGE_PATH=$1

if [ $? -eq 0 ]; then
    docker-compose run --rm --name=polyaxon_python -w /polyaxon/${PACKAGE_PATH} api python ${@:2}
fi
