---
version: 1

kind: experiment

tags: [tensorflow]

declarations:
  conv1_size: 5
  conv1_out: 32
  conv1_activation: 'relu'
  pool1_size: 2
  conv2_size: 5
  conv2_out: 64
  conv2_activation: 'relu'
  pool2_size: 2
  dropout: 0.2
  fc1_size: 1024
  fc1_activation: 'sigmoid'
  optimizer: 'adam'
  log_learning_rate: -3
  batch_size: 100
  epochs: 1

build:
  image: python:2.7
  build_steps:
    - pip install --no-cache-dir -r requirements.txt

run:
  cmd: python model.py --conv1_size={{ conv1_size }} \
                       --conv1_out={{ conv1_out }} \
                       --conv1_activation={{ conv1_activation }} \
                       --pool1_size={{ pool1_size }} \
                       --conv2_size={{ conv2_size }} \
                       --conv2_out={{ conv2_out }} \
                       --conv2_activation={{ conv2_activation }} \
                       --pool2_size={{ pool2_size }} \
                       --dropout={{ dropout }} \
                       --fc1_size={{ fc1_size }} \
                       --fc1_activation={{ fc1_activation }} \
                       --optimizer={{ optimizer }} \
                       --log_learning_rate={{ log_learning_rate }} \
                       --batch_size={{ batch_size }} \
                       --epochs={{ epochs }}
