---
version: 1

kind: group

framework: tensorflow

tags: [examples]

hptuning:
  concurrency: 5
  random_search:
    n_experiments: 50

  matrix:
    conv1_out:
      values: [32, 64, 128]
    conv2_out:
      values: [32, 64, 128]
    conv1_activation:
      values: ['relu', 'sigmoid', 'tanh']
    conv2_activation:
      values: ['relu', 'sigmoid', 'tanh']
    fc1_activation:
      values: ['relu', 'sigmoid', 'tanh']
    dropout:
      uniform: 0:1
    optimizer:
      pvalues: [[adam, 0.5], [rmsprop, 0.3], [sgd, 0.2]]
    log_learning_rate:
      range: [-5, 0, 1]
    epochs:
      values: [1, 3, 7]

declarations:
  conv1_size: 5
  conv2_size: 5
  pool1_size: 2
  pool2_size: 2
  fc1_size: 1024
  batch_size: 100

build:
  image: python:2.7
  build_steps:
    - pip install --no-cache-dir -r requirements.txt

run:
  cmd: python -u model.py --conv1_size={{ conv1_size }} \
                          --conv1_out={{ conv1_out }} \
                          --conv1_activation={{ conv1_activation }} \
                          --pool1_size={{ pool1_size }} \
                          --conv2_size={{ conv2_size }} \
                          --conv2_out={{ conv2_out }} \
                          --conv2_activation={{ conv2_activation }} \
                          --pool2_size={{ pool2_size }} \
                          --dropout={{ dropout }} \
                          --fc1_size={{ fc1_size }} \
                          --fc1_activation={{ fc1_activation }} \
                          --optimizer={{ optimizer }} \
                          --log_learning_rate={{ log_learning_rate }} \
                          --batch_size={{ batch_size }} \
                          --epochs={{ epochs }}
