export enum actionTypes {
  DELETE_TENSORBOARD_REQUEST = 'DELETE_TENSORBOARD_REQUEST',
  DELETE_TENSORBOARD_SUCCESS = 'DELETE_TENSORBOARD_SUCCESS',
  DELETE_TENSORBOARD_ERROR = 'DELETE_TENSORBOARD_ERROR',

  STOP_TENSORBOARD_REQUEST = 'STOP_TENSORBOARD_REQUEST',
  STOP_TENSORBOARD_SUCCESS = 'STOP_TENSORBOARD_SUCCESS',
  STOP_TENSORBOARD_ERROR = 'STOP_TENSORBOARD_ERROR',

  ARCHIVE_TENSORBOARD_REQUEST = 'ARCHIVE_TENSORBOARD_REQUEST',
  ARCHIVE_TENSORBOARD_SUCCESS = 'ARCHIVE_TENSORBOARD_SUCCESS',
  ARCHIVE_TENSORBOARD_ERROR = 'ARCHIVE_TENSORBOARD_ERROR',

  RESTORE_TENSORBOARD_REQUEST = 'RESTORE_TENSORBOARD_REQUEST',
  RESTORE_TENSORBOARD_SUCCESS = 'RESTORE_TENSORBOARD_SUCCESS',
  RESTORE_TENSORBOARD_ERROR = 'RESTORE_TENSORBOARD_ERROR',

  UPDATE_TENSORBOARD_REQUEST = 'UPDATE_TENSORBOARD_REQUEST',
  UPDATE_TENSORBOARD_SUCCESS = 'UPDATE_TENSORBOARD_SUCCESS',
  UPDATE_TENSORBOARD_ERROR = 'UPDATE_TENSORBOARD_ERROR',

  GET_TENSORBOARD_REQUEST = 'GET_TENSORBOARD_REQUEST',
  GET_TENSORBOARD_SUCCESS = 'GET_TENSORBOARD_SUCCESS',
  GET_TENSORBOARD_ERROR = 'GET_TENSORBOARD_ERROR',

  FETCH_TENSORBOARDS_REQUEST = 'FETCH_TENSORBOARDS_REQUEST',
  FETCH_TENSORBOARDS_SUCCESS = 'FETCH_TENSORBOARDS_SUCCESS',
  FETCH_TENSORBOARDS_ERROR = 'FETCH_TENSORBOARDS_ERROR',

  BOOKMARK_TENSORBOARD_REQUEST = 'BOOKMARK_TENSORBOARD_REQUEST',
  BOOKMARK_TENSORBOARD_SUCCESS = 'BOOKMARK_TENSORBOARD_SUCCESS',
  BOOKMARK_TENSORBOARD_ERROR = 'BOOKMARK_TENSORBOARD_ERROR',

  UNBOOKMARK_TENSORBOARD_REQUEST = 'UNBOOKMARK_TENSORBOARD_REQUEST',
  UNBOOKMARK_TENSORBOARD_SUCCESS = 'UNBOOKMARK_TENSORBOARD_SUCCESS',
  UNBOOKMARK_TENSORBOARD_ERROR = 'UNBOOKMARK_TENSORBOARD_ERROR',
}
