import notifier

from actions.registry.webhooks.discord_webhook import DiscordWebHookAction
from actions.registry.webhooks.hipchat_webhook import HipChatWebHookAction
from actions.registry.webhooks.mattermost_webhook import MattermostWebHookAction
from actions.registry.webhooks.pagerduty_webhook import PagerDutyWebHookAction
from actions.registry.webhooks.slack_webhook import SlackWebHookAction
from actions.registry.webhooks.webhook import WebHookAction

notifier.subscribe_action(DiscordWebHookAction)
notifier.subscribe_action(HipChatWebHookAction)
notifier.subscribe_action(MattermostWebHookAction)
notifier.subscribe_action(PagerDutyWebHookAction)
notifier.subscribe_action(SlackWebHookAction)
notifier.subscribe_action(WebHookAction)
