export enum actionTypes {
  CREATE_EXPERIMENT_JOB = 'CREATE_EXPERIMENT_JOB',
  DELETE_EXPERIMENT_JOB = 'DELETE_EXPERIMENT_JOB',
  UPDATE_EXPERIMENT_JOB = 'UPDATE_EXPERIMENT_JOB',

  GET_EXPERIMENT_JOB_REQUEST = 'GET_EXPERIMENT_JOB_REQUEST',
  GET_EXPERIMENT_JOB_SUCCESS = 'GET_EXPERIMENT_JOB_SUCCESS',
  GET_EXPERIMENT_JOB_ERROR = 'GET_EXPERIMENT_JOB_ERROR',

  FETCH_EXPERIMENT_JOBS_REQUEST = 'FETCH_EXPERIMENT_JOBS_REQUEST',
  FETCH_EXPERIMENT_JOBS_SUCCESS = 'FETCH_EXPERIMENT_JOBS_SUCCESS',
  FETCH_EXPERIMENT_JOBS_ERROR = 'FETCH_EXPERIMENT_JOBS_ERROR',
}
