// Copyright 2018-2020 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package projects_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/polyaxon/sdks/go/http_client/v1/service_model"
)

// ProjectsV1CreateProjectReader is a Reader for the ProjectsV1CreateProject structure.
type ProjectsV1CreateProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsV1CreateProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectsV1CreateProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewProjectsV1CreateProjectNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewProjectsV1CreateProjectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewProjectsV1CreateProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewProjectsV1CreateProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectsV1CreateProjectOK creates a ProjectsV1CreateProjectOK with default headers values
func NewProjectsV1CreateProjectOK() *ProjectsV1CreateProjectOK {
	return &ProjectsV1CreateProjectOK{}
}

/*ProjectsV1CreateProjectOK handles this case with default header values.

A successful response.
*/
type ProjectsV1CreateProjectOK struct {
	Payload *service_model.V1Project
}

func (o *ProjectsV1CreateProjectOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/projects/create][%d] projectsV1CreateProjectOK  %+v", 200, o.Payload)
}

func (o *ProjectsV1CreateProjectOK) GetPayload() *service_model.V1Project {
	return o.Payload
}

func (o *ProjectsV1CreateProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1Project)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsV1CreateProjectNoContent creates a ProjectsV1CreateProjectNoContent with default headers values
func NewProjectsV1CreateProjectNoContent() *ProjectsV1CreateProjectNoContent {
	return &ProjectsV1CreateProjectNoContent{}
}

/*ProjectsV1CreateProjectNoContent handles this case with default header values.

No content.
*/
type ProjectsV1CreateProjectNoContent struct {
	Payload interface{}
}

func (o *ProjectsV1CreateProjectNoContent) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/projects/create][%d] projectsV1CreateProjectNoContent  %+v", 204, o.Payload)
}

func (o *ProjectsV1CreateProjectNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *ProjectsV1CreateProjectNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsV1CreateProjectForbidden creates a ProjectsV1CreateProjectForbidden with default headers values
func NewProjectsV1CreateProjectForbidden() *ProjectsV1CreateProjectForbidden {
	return &ProjectsV1CreateProjectForbidden{}
}

/*ProjectsV1CreateProjectForbidden handles this case with default header values.

You don't have permission to access the resource.
*/
type ProjectsV1CreateProjectForbidden struct {
	Payload interface{}
}

func (o *ProjectsV1CreateProjectForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/projects/create][%d] projectsV1CreateProjectForbidden  %+v", 403, o.Payload)
}

func (o *ProjectsV1CreateProjectForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *ProjectsV1CreateProjectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsV1CreateProjectNotFound creates a ProjectsV1CreateProjectNotFound with default headers values
func NewProjectsV1CreateProjectNotFound() *ProjectsV1CreateProjectNotFound {
	return &ProjectsV1CreateProjectNotFound{}
}

/*ProjectsV1CreateProjectNotFound handles this case with default header values.

Resource does not exist.
*/
type ProjectsV1CreateProjectNotFound struct {
	Payload interface{}
}

func (o *ProjectsV1CreateProjectNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/projects/create][%d] projectsV1CreateProjectNotFound  %+v", 404, o.Payload)
}

func (o *ProjectsV1CreateProjectNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *ProjectsV1CreateProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsV1CreateProjectDefault creates a ProjectsV1CreateProjectDefault with default headers values
func NewProjectsV1CreateProjectDefault(code int) *ProjectsV1CreateProjectDefault {
	return &ProjectsV1CreateProjectDefault{
		_statusCode: code,
	}
}

/*ProjectsV1CreateProjectDefault handles this case with default header values.

An unexpected error response
*/
type ProjectsV1CreateProjectDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// Code gets the status code for the projects v1 create project default response
func (o *ProjectsV1CreateProjectDefault) Code() int {
	return o._statusCode
}

func (o *ProjectsV1CreateProjectDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/{owner}/projects/create][%d] ProjectsV1_CreateProject default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectsV1CreateProjectDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *ProjectsV1CreateProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
