#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR=$DIR/..
source $DIR/environment

$DIR/check
if [ $? -eq 0 ]; then
    echo "build api"
    echo "========================"
    docker-compose build api $*
    echo "========================"
fi
