import activitylogs

from event_manager.events import notebook

activitylogs.subscribe(notebook.NotebookStartedTriggeredEvent)
activitylogs.subscribe(notebook.NotebookSoppedTriggeredEvent)
activitylogs.subscribe(notebook.NotebookViewedEvent)
