import activitylogs

from event_manager.events import notebook

activitylogs.subscribe(notebook.NotebookStartedTriggeredEvent)
activitylogs.subscribe(notebook.NotebookSoppedTriggeredEvent)
activitylogs.subscribe(notebook.NotebookViewedEvent)
activitylogs.subscribe(notebook.NotebookStatusesViewedEvent)
activitylogs.subscribe(notebook.NotebookUpdatedEvent)
activitylogs.subscribe(notebook.NotebookBookmarkedEvent)
activitylogs.subscribe(notebook.NotebookUnBookmarkedEvent)
activitylogs.subscribe(notebook.NotebookDeletedTriggeredEvent)
activitylogs.subscribe(notebook.NotebookArchivedEvent)
activitylogs.subscribe(notebook.NotebookRestoredEvent)
