import activitylogs

from event_manager.events import project

activitylogs.subscribe(project.ProjectCreatedEvent)
activitylogs.subscribe(project.ProjectUpdatedEvent)
activitylogs.subscribe(project.ProjectDeletedTriggeredEvent)
activitylogs.subscribe(project.ProjectViewedEvent)
activitylogs.subscribe(project.ProjectExperimentsViewedEvent)
activitylogs.subscribe(project.ProjectExperimentGroupsViewedEvent)
activitylogs.subscribe(project.ProjectJobsViewedEvent)
activitylogs.subscribe(project.ProjectBuildsViewedEvent)
activitylogs.subscribe(project.ProjectTensorboardsViewedEvent)
