import activitylogs

from event_manager.events import tensorboard

activitylogs.subscribe(tensorboard.TensorboardStartedEvent)
activitylogs.subscribe(tensorboard.TensorboardSoppedEvent)
activitylogs.subscribe(tensorboard.TensorboardViewedEvent)
