import activitylogs

from event_manager.events import tensorboard

activitylogs.subscribe(tensorboard.TensorboardStartedTriggeredEvent)
activitylogs.subscribe(tensorboard.TensorboardSoppedTriggeredEvent)
activitylogs.subscribe(tensorboard.TensorboardViewedEvent)
